# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set version env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload binaries to release
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: Uniporter-${{ env.RELEASE_VERSION }}.jar
          path: build/libs/Uniporter-${{ env.RELEASE_VERSION }}.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}
